apiVersion: v1
kind: ServiceAccount
metadata:
  name: term-project-server
  annotations:
    iam.gke.io/gcp-service-account: term-project-server@cedar-booth-287414.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: term-project-worker
  annotations:
    iam.gke.io/gcp-service-account: term-project-worker@cedar-booth-287414.iam.gserviceaccount.com
---
kind: Service
apiVersion: v1
metadata:
  name: "rabbitmq"
spec:
  selector:
    app: "rabbitmq"
  ports:
    - protocol: "TCP"
      port: 5672
      targetPort: 5672
---
kind: Service
apiVersion: v1
metadata:
  name: "server"
spec:
  type: NodePort
  selector:
    app: "server"
  ports:
    - name: server
      port: 3001
      targetPort: 3001
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "server"
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "server"
              servicePort: 3001
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: master
          image: rabbitmq
          ports:
            - containerPort: 5672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: term-project
                  key: RABBITMQ_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: term-project
                  key: RABBITMQ_PWD
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.1"
            limits:
              memory: "500Mi"
              cpu: "0.4"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: worker
    spec:
      serviceAccountName: term-project-worker
      volumes:
        - name: cloudsql
          emptyDir: { }
      containers:
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.16
          command:
            - "/cloud_sql_proxy"
            - "-instances=cedar-booth-287414:us-central1:term-project=tcp:5432"
          volumeMounts:
            - name: cloudsql
              mountPath: /cloudsql
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.2"
        - name: master
          image: gcr.io/cedar-booth-287414/term-project-worker
          volumeMounts:
            - name: cloudsql
              mountPath: /cloudsql
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: term-project
                  key: RABBITMQ_USER
            - name: RABBITMQ_PWD
              valueFrom:
                secretKeyRef:
                  name: term-project
                  key: RABBITMQ_PWD
            - name: RABBITMQ_PORT
              value: "5672"
            - name: WORK_EXCHANGE
              value: "processing-exchange"
            - name: WORK_QUEUE
              value: "processing-queue"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: PG_DATABASE
              value: "term_project"
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: term-project
                  key: PG_USER
            - name: PG_PWD
              valueFrom:
                secretKeyRef:
                  name: term-project
                  key: PG_PWD
            - name: PG_HOST
              value: "localhost"
            - name: AUDIO_BUCKET
              value: "term-project-audio"
          resources:
            requests:
              memory: "1024Mi"
              cpu: "0.5"
            limits:
              memory: "2048Mi"
              cpu: "2.0"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccountName: term-project-server
      volumes:
        - name: cloudsql
          emptyDir: { }
      containers:
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.16
          command:
            - "/cloud_sql_proxy"
            - "-instances=cedar-booth-287414:us-central1:term-project=tcp:5432"
          volumeMounts:
            - name: cloudsql
              mountPath: /cloudsql
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.2"
        - name: server
          image: gcr.io/cedar-booth-287414/term-project-server
          volumeMounts:
            - name: cloudsql
              mountPath: /cloudsql
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
          ports:
            - containerPort: 3001
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: term-project
                  key: RABBITMQ_USER
            - name: RABBITMQ_PWD
              valueFrom:
                secretKeyRef:
                  name: term-project
                  key: RABBITMQ_PWD
            - name: RABBITMQ_PORT
              value: "5672"
            - name: WORK_EXCHANGE
              value: "processing-exchange"
            - name: WORK_QUEUE
              value: "processing-queue"
            - name: PG_DATABASE
              value: "term_project"
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: term-project
                  key: PG_USER
            - name: PG_PWD
              valueFrom:
                secretKeyRef:
                  name: term-project
                  key: PG_PWD
            - name: PG_HOST
              value: "localhost"
            - name: AUDIO_BUCKET
              value: "term-project-audio"
            - name: PORT
              value: "3001"
            - name: NODE_ENV
              value: "development"
            - name: REQUEST_LOGGING
              value: "true"
            - name: CORS_ORIGIN
              value: "http://localhost:3000"
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.2"
